<?php

namespace App\OpenApi\Schemas\Tasks;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'StoreTaskRequest', required: ['title', 'task_date', 'start_at', 'employee_ids'], properties: [new OA\Property(property: 'title', type: 'string', maxLength: 255, example: 'Inspect warehouse safety equipment'), new OA\Property(property: 'description', type: 'string', nullable: true, example: 'Check extinguishers and emergency exits.'), new OA\Property(property: 'priority', type: 'string', enum: ['low', 'medium', 'high', 'urgent'], example: 'medium'), new OA\Property(property: 'reminder_interval_minutes', type: 'integer', nullable: true, example: 60), new OA\Property(property: 'task_date', type: 'string', format: 'date', example: '2026-05-12'), new OA\Property(property: 'start_at', type: 'string', format: 'date-time', example: '2026-05-12T09:00:00+00:00'), new OA\Property(property: 'end_at', type: 'string', format: 'date-time', nullable: true, example: '2026-05-12T11:00:00+00:00'), new OA\Property(property: 'employee_ids', type: 'array', minItems: 1, items: new OA\Items(type: 'integer'), example: [12, 13]), new OA\Property(property: 'assignment_notes', type: 'object', additionalProperties: new OA\AdditionalProperties(type: 'string', nullable: true), nullable: true, example: ['12' => 'Use entrance B.'])], type: 'object')]
#[OA\Schema(schema: 'UpdateTaskRequest', properties: [new OA\Property(property: 'title', type: 'string', maxLength: 255, example: 'Inspect warehouse safety equipment'), new OA\Property(property: 'description', type: 'string', nullable: true, example: 'Updated description.'), new OA\Property(property: 'priority', type: 'string', enum: ['low', 'medium', 'high', 'urgent'], example: 'medium'), new OA\Property(property: 'reminder_interval_minutes', type: 'integer', nullable: true, example: 60), new OA\Property(property: 'task_date', type: 'string', format: 'date', example: '2026-05-12'), new OA\Property(property: 'start_at', type: 'string', format: 'date-time', example: '2026-05-12T09:00:00+00:00'), new OA\Property(property: 'end_at', type: 'string', format: 'date-time', nullable: true, example: '2026-05-12T11:00:00+00:00'), new OA\Property(property: 'assignment_notes', type: 'object', additionalProperties: new OA\AdditionalProperties(type: 'string', nullable: true), nullable: true, example: ['12' => 'Updated note.'])], type: 'object')]
#[OA\Schema(schema: 'TaskResponse', required: ['success', 'message', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Task retrieved successfully.'), new OA\Property(property: 'data', ref: '#/components/schemas/Task')], type: 'object')]
#[OA\Schema(schema: 'TasksCollectionResponse', required: ['success', 'message', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Tasks retrieved successfully.'), new OA\Property(property: 'data', properties: [new OA\Property(property: 'tasks', type: 'array', items: new OA\Items(ref: '#/components/schemas/Task'))], type: 'object')], type: 'object')]
#[OA\Schema(schema: 'PaginatedTasksResponse', required: ['success', 'message', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Tasks retrieved successfully.'), new OA\Property(property: 'data', properties: [new OA\Property(property: 'tasks', type: 'array', items: new OA\Items(ref: '#/components/schemas/Task')), new OA\Property(property: 'pagination', ref: '#/components/schemas/PaginationMeta')], type: 'object')], type: 'object')]
final class TaskSupportSchemas {}
