<?php

namespace App\OpenApi\Paths;

use OpenApi\Attributes as OA;

final class AssignmentsDocumentation
{
    #[OA\Get(path: '/api/assignments/my-current', operationId: 'assignmentsMyCurrent', summary: 'Get current assignment', description: 'Employee-only endpoint returning the latest pending or active assignment, or null.', tags: ['Assignments'], security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Current assignment retrieved.', content: new OA\JsonContent(ref: '#/components/schemas/MyCurrentAssignmentResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Employee role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse'))])]
    public function myCurrent(): void {}

    #[OA\Patch(path: '/api/assignments/{assignment}/accept', operationId: 'assignmentsAccept', summary: 'Accept assignment', description: 'Employee-only. The assignment must belong to the authenticated employee.', tags: ['Assignments'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'assignment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 301)], responses: [new OA\Response(response: 200, description: 'Assignment accepted.', content: new OA\JsonContent(ref: '#/components/schemas/AssignmentResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Employee role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Assignment not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Assignment cannot be accepted.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse'))])]
    public function accept(): void {}

    #[OA\Patch(path: '/api/assignments/{assignment}/reject', operationId: 'assignmentsReject', summary: 'Reject assignment', tags: ['Assignments'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'assignment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 301)], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['rejection_reason'], properties: [new OA\Property(property: 'rejection_reason', type: 'string', minLength: 3, maxLength: 1000, example: 'I am unavailable for this schedule.')], type: 'object')), responses: [new OA\Response(response: 200, description: 'Assignment rejected.', content: new OA\JsonContent(ref: '#/components/schemas/AssignmentResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Employee role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Assignment not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Assignment cannot be rejected.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function reject(): void {}

    #[OA\Patch(path: '/api/assignments/{assignment}/complete', operationId: 'assignmentsComplete', summary: 'Complete assignment', description: 'Employee-only. Only active assignments can be completed.', tags: ['Assignments'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'assignment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 301)], responses: [new OA\Response(response: 200, description: 'Assignment completed.', content: new OA\JsonContent(ref: '#/components/schemas/AssignmentResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Employee role required, user inactive, or policy denied.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Assignment not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Only active assignments can be completed.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse'))])]
    public function complete(): void {}
}
