<?php

namespace App\OpenApi\Paths;

use OpenApi\Attributes as OA;

final class ReportsDocumentation
{
    #[OA\Post(path: '/api/location/request', operationId: 'locationRequest', summary: 'Request employee live locations', description: 'Admin-only. Starts a live tracking session for selected active employees or all active employees when employee_ids is omitted.', tags: ['Reports'], security: [['bearerAuth' => []]], requestBody: new OA\RequestBody(required: false, content: new OA\JsonContent(properties: [new OA\Property(property: 'employee_ids', type: 'array', nullable: true, items: new OA\Items(type: 'integer'), example: [12, 13]), new OA\Property(property: 'interval_seconds', type: 'integer', minimum: 1, maximum: 60, nullable: true, default: 5, example: 5)], type: 'object')), responses: [new OA\Response(response: 200, description: 'Location request sent.', content: new OA\JsonContent(ref: '#/components/schemas/LocationRequestResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function request(): void {}

    #[OA\Get(path: '/api/location/live', operationId: 'locationLive', summary: 'List live employee locations', description: 'Admin-only live location report for all employees with a current live location row.', tags: ['Reports'], security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Live locations retrieved.', content: new OA\JsonContent(ref: '#/components/schemas/LiveLocationsResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse'))])]
    public function live(): void {}

    #[OA\Get(path: '/api/location/live/{userId}', operationId: 'locationLiveForUser', summary: 'Get live employee location', description: 'Admin-only live location report for a single employee user ID.', tags: ['Reports'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'userId', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 12)], responses: [new OA\Response(response: 200, description: 'Employee location retrieved.', content: new OA\JsonContent(ref: '#/components/schemas/LiveLocationResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Location not found for this employee.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse'))])]
    public function liveForUser(): void {}

    #[OA\Post(path: '/api/location/sync', operationId: 'locationSync', summary: 'Sync batched employee locations', description: 'Employee-only batched tracking update for an active tracking session. Points must be a list of 1 to 500 entries.', tags: ['Reports'], security: [['bearerAuth' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['tracking_session_id', 'points'], properties: [new OA\Property(property: 'tracking_session_id', type: 'integer', example: 55), new OA\Property(property: 'points', type: 'array', minItems: 1, maxItems: 500, items: new OA\Items(ref: '#/components/schemas/LocationPoint'))], type: 'object')), responses: [new OA\Response(response: 200, description: 'Location batch synced.', content: new OA\JsonContent(ref: '#/components/schemas/EmptyDataResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Employee role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function sync(): void {}

    #[OA\Post(path: '/api/location/submit', operationId: 'locationSubmit', summary: 'Submit single employee location', description: 'Employee-only legacy single-point location submission. Deprecated in favor of POST /api/location/sync.', tags: ['Reports'], security: [['bearerAuth' => []]], deprecated: true, requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['latitude', 'longitude'], properties: [new OA\Property(property: 'latitude', type: 'number', format: 'float', minimum: -90, maximum: 90, example: 33.5138), new OA\Property(property: 'longitude', type: 'number', format: 'float', minimum: -180, maximum: 180, example: 36.2765), new OA\Property(property: 'accuracy', type: 'number', format: 'float', nullable: true, minimum: 0, example: 8.5)], type: 'object')), responses: [new OA\Response(response: 200, description: 'Location submitted.', content: new OA\JsonContent(ref: '#/components/schemas/EmptyDataResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Employee role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function submit(): void {}
}
