<?php

namespace App\OpenApi\Paths;

use OpenApi\Attributes as OA;

final class TasksDocumentation
{
    #[OA\Get(path: '/api/tasks', operationId: 'tasksIndex', summary: 'List accessible tasks', description: 'Authenticated admins receive all tasks; employees receive only tasks assigned to them. This endpoint is not paginated.', tags: ['Tasks'], security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Tasks retrieved.', content: new OA\JsonContent(ref: '#/components/schemas/TasksCollectionResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Inactive user.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse'))])]
    public function index(): void {}

    #[OA\Get(
        path: '/api/admin/tasks',
        operationId: 'tasksAdminIndex',
        summary: 'List tasks for admin',
        description: 'Admin-only paginated task listing with search and filters.',
        tags: ['Tasks'],
        security: [['bearerAuth' => []]],
        parameters: [
            new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string', maxLength: 255), example: 'inspection'),
            new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['pending', 'active', 'completed', 'cancelled']), example: 'pending'),
            new OA\Parameter(name: 'assignment_status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['pending', 'active', 'completed', 'cancelled', 'rejected']), example: 'active'),
            new OA\Parameter(name: 'employee_id', in: 'query', schema: new OA\Schema(type: 'integer'), example: 12),
            new OA\Parameter(name: 'task_date', in: 'query', schema: new OA\Schema(type: 'string', format: 'date'), example: '2026-05-12'),
            new OA\Parameter(name: 'date_from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date'), example: '2026-05-01'),
            new OA\Parameter(name: 'date_to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date'), example: '2026-05-31'),
            new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 15), example: 15),
        ],
        responses: [
            new OA\Response(response: 200, description: 'Tasks retrieved.', content: new OA\JsonContent(ref: '#/components/schemas/PaginatedTasksResponse')),
            new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')),
            new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')),
            new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse')),
        ],
    )]
    public function adminIndex(): void {}

    #[OA\Post(path: '/api/tasks', operationId: 'tasksStore', summary: 'Create task', description: 'Admin-only task creation. All selected users must be active employees. Returns 409 when selected employees have conflicting active assignments.', tags: ['Tasks'], security: [['bearerAuth' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/StoreTaskRequest')), responses: [new OA\Response(response: 201, description: 'Task created.', content: new OA\JsonContent(ref: '#/components/schemas/TaskResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 409, description: 'Assignment conflict.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function store(): void {}

    #[OA\Get(path: '/api/tasks/{task}', operationId: 'tasksShow', summary: 'Show task', description: 'Admins can view any task. Employees can only view assigned tasks; unauthorized employee access returns 404 to avoid ID enumeration.', tags: ['Tasks'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 101)], responses: [new OA\Response(response: 200, description: 'Task retrieved.', content: new OA\JsonContent(ref: '#/components/schemas/TaskResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Inactive user.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Task not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse'))])]
    public function show(): void {}

    #[OA\Put(path: '/api/tasks/{task}', operationId: 'tasksUpdatePut', summary: 'Update task', tags: ['Tasks'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 101)], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/UpdateTaskRequest')), responses: [new OA\Response(response: 200, description: 'Task updated.', content: new OA\JsonContent(ref: '#/components/schemas/TaskResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Task not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Completed or cancelled task cannot be changed.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    #[OA\Patch(path: '/api/tasks/{task}', operationId: 'tasksUpdatePatch', summary: 'Partially update task', tags: ['Tasks'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 101)], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/UpdateTaskRequest')), responses: [new OA\Response(response: 200, description: 'Task updated.', content: new OA\JsonContent(ref: '#/components/schemas/TaskResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Task not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Completed or cancelled task cannot be changed.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function update(): void {}

    #[OA\Patch(path: '/api/tasks/{task}/cancel', operationId: 'tasksCancel', summary: 'Cancel task', tags: ['Tasks'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 101)], requestBody: new OA\RequestBody(required: false, content: new OA\JsonContent(properties: [new OA\Property(property: 'cancel_reason', type: 'string', maxLength: 500, nullable: true, example: 'Schedule changed.')], type: 'object')), responses: [new OA\Response(response: 200, description: 'Task cancelled.', content: new OA\JsonContent(ref: '#/components/schemas/TaskResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Task not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Completed or cancelled task cannot be changed.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function cancel(): void {}

    #[OA\Patch(path: '/api/tasks/{task}/activate', operationId: 'tasksActivate', summary: 'Activate task', description: 'Admin-only. Only pending tasks can be activated.', tags: ['Tasks'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 101)], responses: [new OA\Response(response: 200, description: 'Task activated.', content: new OA\JsonContent(ref: '#/components/schemas/TaskResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Task not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse')), new OA\Response(response: 409, description: 'Only pending tasks can be activated.', content: new OA\JsonContent(ref: '#/components/schemas/ApiErrorResponse'))])]
    public function activate(): void {}

    #[OA\Delete(path: '/api/admin/tasks/{task}', operationId: 'tasksDestroy', summary: 'Delete task', description: 'Admin-only soft delete. Pending or active tasks are cancelled before deletion.', tags: ['Tasks'], security: [['bearerAuth' => []]], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'), example: 101)], responses: [new OA\Response(response: 200, description: 'Task deleted.', content: new OA\JsonContent(ref: '#/components/schemas/DeletedCountResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 404, description: 'Task not found.', content: new OA\JsonContent(ref: '#/components/schemas/NotFoundResponse'))])]
    public function destroy(): void {}

    #[OA\Post(path: '/api/admin/tasks/bulk-delete', operationId: 'tasksBulkDelete', summary: 'Bulk delete tasks', tags: ['Tasks'], security: [['bearerAuth' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['task_ids'], properties: [new OA\Property(property: 'task_ids', type: 'array', minItems: 1, items: new OA\Items(type: 'integer'), example: [101, 102])], type: 'object')), responses: [new OA\Response(response: 200, description: 'Tasks deleted.', content: new OA\JsonContent(ref: '#/components/schemas/DeletedCountResponse')), new OA\Response(response: 401, description: 'Unauthenticated.', content: new OA\JsonContent(ref: '#/components/schemas/UnauthenticatedResponse')), new OA\Response(response: 403, description: 'Admin role required or user inactive.', content: new OA\JsonContent(ref: '#/components/schemas/ForbiddenResponse')), new OA\Response(response: 422, description: 'Validation error.', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
    public function bulkDelete(): void {}
}
